export const mockCategories = [
  { id: 'cat-1', name: 'Chicken', nameTe: 'చికెన్', slug: 'chicken', icon: '🍗' },
  { id: 'cat-2', name: 'Mutton', nameTe: 'మటన్', slug: 'mutton', icon: '🥩' },
  { id: 'cat-3', name: 'Thali Combos', nameTe: 'థాలీ కాంబోలు', slug: 'thali', icon: '🍱' },
  { id: 'cat-4', name: 'Specials', nameTe: 'స్పెషల్స్', slug: 'specials', icon: '⭐' },
]

export const mockMenuItems = [
  {
    id: 'item-1',
    categoryId: 'cat-1',
    name: 'Chicken & Rice',
    nameTe: 'చికెన్ & రైస్',
    description: 'Tender chicken curry with steamed rice — authentic Telangana village style.',
    descriptionTe: 'మెత్తటి చికెన్ కూర మరియు వేయించిన అన్నం — అసలైన తెలంగాణ గ్రామ శైలిలో.',
    isVeg: false,
    isAvailable: true,
    isBestseller: true,
    isSundaySpecial: false,
    image: '/images/chicken-rice.jpg',
    variants: [
      { id: 'v1-1', label: '1 Person', labelTe: '1 వ్యక్తి', price: 199 },
      { id: 'v1-2', label: '2 Persons', labelTe: '2 వ్యక్తులు', price: 349 },
      { id: 'v1-3', label: '4 Persons', labelTe: '4 వ్యక్తులు', price: 699 },
    ],
  },
  {
    id: 'item-2',
    categoryId: 'cat-2',
    name: 'Mutton & Rice',
    nameTe: 'మటన్ & రైస్',
    description: 'Slow-cooked mutton curry with fragrant rice — a Mallannapeta classic.',
    descriptionTe: 'నిదానంగా వండిన మటన్ కూర మరియు సుగంధ అన్నం — మల్లన్నపేట క్లాసిక్.',
    isVeg: false,
    isAvailable: true,
    isBestseller: true,
    isSundaySpecial: false,
    image: '/images/mutton-rice.jpg',
    variants: [
      { id: 'v2-1', label: '1 Person', labelTe: '1 వ్యక్తి', price: 299 },
      { id: 'v2-2', label: '2 Persons', labelTe: '2 వ్యక్తులు', price: 549 },
      { id: 'v2-3', label: '4 Persons', labelTe: '4 వ్యక్తులు', price: 1099 },
    ],
  },
  {
    id: 'item-3',
    categoryId: 'cat-3',
    name: 'Thali Combo',
    nameTe: 'థాలీ కాంబో',
    description: 'Rice + Special Curry + Pappu + Charu + Curd + Appadam + Chutney — complete meal.',
    descriptionTe: 'అన్నం + స్పెషల్ కూర + పప్పు + చారు + పెరుగు + అప్పడం + చట్నీ — పూర్తి భోజనం.',
    isVeg: false,
    isAvailable: true,
    isBestseller: false,
    isSundaySpecial: false,
    image: '/images/thali.jpg',
    variants: [
      { id: 'v3-1', label: '1 Person', labelTe: '1 వ్యక్తి', price: 199 },
      { id: 'v3-2', label: '2 Persons', labelTe: '2 వ్యక్తులు', price: 349 },
      { id: 'v3-3', label: '4 Persons', labelTe: '4 వ్యక్తులు', price: 699 },
    ],
  },
  {
    id: 'item-4',
    categoryId: 'cat-4',
    name: 'Boti',
    nameTe: 'బోటి',
    description: 'Tender goat intestine slow-cooked in rich Telangana masala — a village delicacy for true foodies.',
    descriptionTe: 'మసాలాలో వండిన మేక ప్రేవులు — నిజమైన ఆహార ప్రేమికుల కోసం.',
    isVeg: false,
    isAvailable: true,
    isBestseller: false,
    isSundaySpecial: true,
    image: '/images/boti.jpg',
    variants: [{ id: 'v4-1', label: '1 KG', labelTe: '1 కేజీ', price: 749 }],
  },
  {
    id: 'item-5',
    categoryId: 'cat-4',
    name: 'Thalakaya',
    nameTe: 'తలకాయ',
    description: 'Goat head curry — a traditional weekend delicacy, rich in flavor and heritage.',
    descriptionTe: 'మేక తల కూర — సంప్రదాయ వారాంత రుచి, రుచి మరియు వారసత్వంతో సమృద్ధి.',
    isVeg: false,
    isAvailable: true,
    isBestseller: false,
    isSundaySpecial: true,
    image: '/images/thalakaya.jpg',
    variants: [{ id: 'v5-1', label: '1 KG', labelTe: '1 కేజీ', price: 1100 }],
  },
]

export const mockSundaySpecial = {
  id: 'ss-1',
  menuItemId: 'item-4',
  menuItem: mockMenuItems[3],
  specialPrice: 699,
  isActive: true,
  weekStarting: new Date().toISOString(),
  bannerHeadline: 'This Sunday Only',
  bannerHeadlineTe: 'ఈ ఆదివారం మాత్రమే',
}

export const mockOrders = [
  {
    id: 'ord-1',
    orderNumber: 'MK-2024-001',
    status: 'DELIVERED',
    items: [
      { name: 'Chicken & Rice', nameTe: 'చికెన్ & రైస్', variant: '2 Persons', qty: 1, price: 349 },
      { name: 'Boti', nameTe: 'బోటి', variant: '1 KG', qty: 1, price: 749 },
    ],
    subtotal: 1098,
    deliveryFee: 40,
    total: 1138,
    placedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    address: '12-3/4, Gandhi Nagar, Jagtial, Telangana 505327',
  },
  {
    id: 'ord-2',
    orderNumber: 'MK-2024-002',
    status: 'PREPARING',
    items: [
      { name: 'Mutton & Rice', nameTe: 'మటన్ & రైస్', variant: '4 Persons', qty: 1, price: 1099 },
    ],
    subtotal: 1099,
    deliveryFee: 40,
    total: 1139,
    placedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    deliveredAt: null,
    address: '45, Sai Nagar, Jagtial, Telangana 505327',
  },
]

export const kitchenInfo = {
  name: 'Mallannapeta Kitchen',
  nameTe: 'మల్లన్నపేట కిచెన్',
  phone: '+91 79930 40100',
  email: 'mallanapetkitchen@gmail.com',
  instagram: 'https://instagram.com/Mallanapeta_kitchen',
  whatsapp: 'https://wa.me/917993040100',
  isOpen: true,
  openingHours: '10:00 AM – 9:00 PM',
  openingHoursTe: 'ఉ. 10:00 – రా. 9:00',
  minOrderValue: 100,
}
